### ISSUE TITLE
Visibility check as true in smoke

### ISSUE THREAD

**Issue by JohnPythonJohnRename** [TheCruZ/Direct-EFI-Apex-Cheat#2]
Hi. Your work is awesome.
A small question about whether this is implementable by some offset.

As your post stated, we could easily check the offset 
```
//store this somewhere globally:
float visiblePlayerInfo[75] = {};
 
 
//do this to know if visible or not:
bool visible = false;
float LastVisibleTime = 0.f;
read<float>(entity + OFFSET_LAST_VISIBLE_TIME, &LastVisibleTime);
 
visible = LastVisibleTime > 0.f && LastVisibleTime > visiblePlayerInfo[index];
visiblePlayerInfo[index] = LastVisibleTime;
```
**What if the people are in smoke and you want to treat it as visible?**
Do you know is there any offset that indicates whether the object is in smoke?
Just curious if this could even be done **not** by considering extra offset since I believe such offset is difficult to find.

**Comment by TheCruZ** [comment]
I don't know if anything can help here, you will need to research by yourself, sorry
