### ISSUE TITLE
Weapon ESP

### ISSUE THREAD

**Issue by JohnPythonJohnRename** [TheCruZ/Direct-EFI-Apex-Cheat#3]
Thanks for the great work.

Do you know if there is any code that could reference            if I want to add an overlay to the game to show where are the weapon and their name?

https://github.com/TheCruZ/Direct-EFI-Apex-Cheat/blob/4f31a44634d6be8a9e923e84c68f83a20dbd09bb/CRZAimbot/Main.cpp#L456

Maybe I guess there is some offset  OFFSET_WEAPONLIST that could be used as 

`weaponlist = GameBaseAddress + TOFFSET(OFFSET_WEAPONLIST );`

and then for each of them, we process their location etc.

**Comment by TheCruZ** [comment]
They are in the same entity list, you have to go through all the entities and search how to filter the weapons
